services:
  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  json-server:
    image: node:22
    working_dir: /app
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "500"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run test"
